(part "LDD-1500L"
    (packageRef "LDD1500L")
    (interface
        (port "1" (symbPinId 1) (portName "-VIN_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-VIN_2") (portType INOUT))
        (port "11" (symbPinId 3) (portName "-VOUT_1") (portType INOUT))
        (port "12" (symbPinId 4) (portName "-VOUT_2") (portType INOUT))
        (port "13" (symbPinId 5) (portName "+VOUT_1") (portType INOUT))
        (port "14" (symbPinId 6) (portName "+VOUT_2") (portType INOUT))
        (port "21" (symbPinId 7) (portName "PWM_+ANALOG_DIM") (portType INOUT))
        (port "23" (symbPinId 8) (portName "+VIN_1") (portType INOUT))
        (port "24" (symbPinId 9) (portName "+VIN_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Manufacturer_Name" "Mean Well")
    (property "Manufacturer_Part_Number" "LDD-1500L")
    (property "Arrow_Part_Number" "LDD-1500L")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ldd-1500l/mean-well-enterprises")
    (property "Mouser_Part_Number" "709-LDD-1500L")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/MEAN-WELL/LDD-1500L?qs=JK6Bpmia%2FmsTbFwcpjJldw%3D%3D")
    (property "Description" "LED Power Supplies 6-36Vin 2-30V 1500mA Pin DC-DC LED Driver")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/LDD-1500L.pdf")
    (property "symbolName1" "LDD-1500L")
)
